apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-application
  labels:
    app: nodejs-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-application
  template:
    metadata:
      labels:
        app: nodejs-application
    spec:
      containers:
        - name: nodejs-application
          image: sureshpsl/node-js-sample:1.0 # Replace with your Docker hub repository name and tag
          ports:
            - containerPort: 5000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db-service:3306/tododb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Root@123
      imagePullSecrets:
        - name: my-registry-secret # Docker Hub credentials secret
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-application-service
  labels:
    app: nodejs-application
spec:
  selector:
    app: nodejs-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort # Expose the application externally