---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-js-pv
spec:
  capacity:
    storage: 1Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/node-js # Directory on the host VM, adjust as needed
    type: DirectoryOrCreate # Ensures the directory is created if it doesn't exist
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-js-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Must match the PV capacity